import { Link, useParams } from 'react-router-dom'
import { useProjects } from '../context/ProjectsContext.jsx'
import { GitBranchIcon } from '../components/icons.jsx'

// ---------------------------------------------------------------------------
// ProjectDiagrams
// ---------------------------------------------------------------------------
// `project.diagrams` only ever gets filled in by a real AI agent generating
// diagrams from the project's requirements - there's no manual "add a
// diagram" button here, and nothing in this app seeds it with invented
// content. Until that agent exists, this page is honestly always the
// empty state below.
//
// The accept/reject/"redo with adjustments" review flow described for
// this page isn't built yet: with no way to produce a real diagram, that
// UI would never actually render anything, so it's deferred until there's
// a real source of diagrams to review.
// ---------------------------------------------------------------------------
export default function ProjectDiagrams() {
  const { id } = useParams()
  const { getProject } = useProjects()
  const project = getProject(id)

  if (!project) {
    return (
      <div>
        <h1 className="text-3xl font-bold text-slate-900">Project not found</h1>
        <p className="mt-1 text-slate-500">
          This project may have been removed.{' '}
          <Link to="/dashboard" className="font-medium text-teal-600 hover:text-teal-500">
            Back to Dashboard
          </Link>
        </p>
      </div>
    )
  }

  return (
    <div>
      <h1 className="text-3xl font-bold text-slate-900">System Diagrams</h1>
      <p className="mt-1 text-slate-500">
        Review and approve AI-generated diagrams for {project.name}
      </p>

      <div className="mt-6 flex flex-col items-center justify-center rounded-2xl border border-dashed border-slate-300 bg-white p-12 text-center">
        <div className="mb-4 flex h-14 w-14 items-center justify-center rounded-full bg-slate-100">
          <GitBranchIcon className="h-7 w-7 text-slate-400" />
        </div>
        <h2 className="text-lg font-semibold text-slate-900">No diagrams yet</h2>
        <p className="mt-1 max-w-md text-slate-500">
          Diagrams generated by the AI agent will appear here for you to accept, reject, or
          request changes to.
        </p>
      </div>
    </div>
  )
}
