import { useState } from 'react'
import { Link } from 'react-router-dom'
import { useProjects } from '../context/ProjectsContext.jsx'
import Toggle from '../components/Toggle.jsx'
import {
  RobotIcon,
  BellIcon,
  ChatIcon,
  DocumentIcon,
  GitBranchIcon,
  PaletteIcon,
  TrashIcon,
} from '../components/icons.jsx'

const SETTINGS_KEY = 'tadbeer_settings'

const defaultSettings = {
  aiAgent: {
    autoGenerateDiagrams: true,
    autoExtractRequirements: true,
    requireApproval: true,
    slackMonitoring: true,
  },
  notifications: {
    diagramGenerated: true,
    requirementExtracted: true,
    approvalNeeded: true,
    weeklyDigest: false,
  },
  preferences: { language: 'English', theme: 'Light', dateFormat: 'MM/DD/YYYY' },
}

function loadSettings() {
  const saved = localStorage.getItem(SETTINGS_KEY)
  // Merge onto defaults rather than trusting the saved shape outright, so
  // a settings key added later doesn't come back `undefined` for anyone
  // who saved before it existed.
  return saved ? { ...defaultSettings, ...JSON.parse(saved) } : defaultSettings
}

const selectClass =
  'w-full rounded-lg border border-slate-200 px-3.5 py-2.5 text-slate-900 outline-none focus:border-teal-400'

// One row in the AI Agent Settings / Notifications cards: a label, a
// description, and a toggle that persists to localStorage immediately.
function SettingRow({ label, description, checked, onChange }) {
  return (
    <div className="flex items-center justify-between gap-4 py-3 first:pt-0 last:pb-0">
      <div>
        <p className="font-medium text-slate-900">{label}</p>
        <p className="text-sm text-slate-500">{description}</p>
      </div>
      <Toggle checked={checked} onChange={onChange} />
    </div>
  )
}

// One card in Connected Integrations. Reflects the most recently created
// project's real integration value - never a fabricated "Connected"
// status. "Manage" links to that project (where the value actually
// lives) instead of being a dead button with nowhere real to go.
function IntegrationCard({ icon: Icon, iconColorClass, name, value, project }) {
  const isConnected = Boolean(value)
  return (
    <div className="rounded-2xl border border-slate-200 p-5">
      <div className="flex items-center justify-between">
        <div className="flex items-center gap-3">
          <div className={`flex h-10 w-10 items-center justify-center rounded-xl ${iconColorClass}`}>
            <Icon className="h-5 w-5" />
          </div>
          <div>
            <p className="font-semibold text-slate-900">{name}</p>
            <p className={`text-sm ${isConnected ? 'text-green-600' : 'text-slate-400'}`}>
              {isConnected ? 'Connected' : 'Not connected'}
            </p>
          </div>
        </div>
        <span className={`h-2.5 w-2.5 rounded-full ${isConnected ? 'bg-green-500' : 'bg-slate-300'}`} />
      </div>
      <p className="mt-3 text-sm text-slate-500">{value || 'Nothing connected yet'}</p>
      {isConnected ? (
        <Link
          to={`/projects/${project.id}`}
          className="mt-3 block rounded-lg border border-slate-200 py-2 text-center text-sm font-semibold text-slate-700 transition hover:bg-slate-50"
        >
          Manage
        </Link>
      ) : (
        <button
          disabled
          className="mt-3 w-full cursor-not-allowed rounded-lg border border-slate-200 py-2 text-sm font-semibold text-slate-400"
        >
          Manage
        </button>
      )}
    </div>
  )
}

// ---------------------------------------------------------------------------
// Settings
// ---------------------------------------------------------------------------
// Account-level, not project-scoped. Toggles apply and persist
// immediately; Preferences batches into an explicit "Save Changes" so
// that button actually does something real instead of being decorative.
// Connected Integrations always reflects the most recently created
// project's real integration fields - "Not connected" whenever one was
// left blank, never an invented "Connected" status.
// ---------------------------------------------------------------------------
export default function Settings() {
  const { projects, deleteAllProjects } = useProjects()
  const [settings, setSettings] = useState(loadSettings)
  const [preferencesDraft, setPreferencesDraft] = useState(loadSettings().preferences)
  const [justSaved, setJustSaved] = useState(false)

  const mostRecentProject = projects[0]

  function persist(next) {
    setSettings(next)
    localStorage.setItem(SETTINGS_KEY, JSON.stringify(next))
  }

  function toggleAiAgent(key) {
    persist({ ...settings, aiAgent: { ...settings.aiAgent, [key]: !settings.aiAgent[key] } })
  }

  function toggleNotification(key) {
    persist({
      ...settings,
      notifications: { ...settings.notifications, [key]: !settings.notifications[key] },
    })
  }

  function handlePreferenceChange(event) {
    const { name, value } = event.target
    setPreferencesDraft((previous) => ({ ...previous, [name]: value }))
  }

  function handleSavePreferences() {
    persist({ ...settings, preferences: preferencesDraft })
    setJustSaved(true)
    setTimeout(() => setJustSaved(false), 2000)
  }

  function handleDeleteAllData() {
    if (window.confirm('Permanently delete all project data? This cannot be undone.')) {
      deleteAllProjects()
    }
  }

  return (
    <div>
      <h1 className="text-3xl font-bold text-slate-900">Settings</h1>
      <p className="mt-1 text-slate-500">Configure Tadbeer to work the way you want</p>

      <div className="mt-6 grid grid-cols-1 gap-6 lg:grid-cols-2">
        <div className="rounded-2xl border border-slate-200 bg-white p-6">
          <div className="mb-2 flex items-center gap-2">
            <RobotIcon className="h-5 w-5 text-slate-400" />
            <h2 className="font-semibold text-slate-900">AI Agent Settings</h2>
          </div>
          <p className="mb-3 text-sm text-slate-500">Configure how the AI agent behaves</p>
          <div className="divide-y divide-slate-100">
            <SettingRow
              label="Auto-generate Diagrams"
              description="Automatically create diagrams from requirements"
              checked={settings.aiAgent.autoGenerateDiagrams}
              onChange={() => toggleAiAgent('autoGenerateDiagrams')}
            />
            <SettingRow
              label="Auto-extract Requirements"
              description="Extract requirements from Slack conversations"
              checked={settings.aiAgent.autoExtractRequirements}
              onChange={() => toggleAiAgent('autoExtractRequirements')}
            />
            <SettingRow
              label="Require Approval"
              description="Require PM approval before executing changes"
              checked={settings.aiAgent.requireApproval}
              onChange={() => toggleAiAgent('requireApproval')}
            />
            <SettingRow
              label="Slack Monitoring"
              description="Monitor Slack for project discussions"
              checked={settings.aiAgent.slackMonitoring}
              onChange={() => toggleAiAgent('slackMonitoring')}
            />
          </div>
        </div>

        <div className="rounded-2xl border border-slate-200 bg-white p-6">
          <div className="mb-2 flex items-center gap-2">
            <BellIcon className="h-5 w-5 text-slate-400" />
            <h2 className="font-semibold text-slate-900">Notifications</h2>
          </div>
          <p className="mb-3 text-sm text-slate-500">Choose what you want to be notified about</p>
          <div className="divide-y divide-slate-100">
            <SettingRow
              label="Diagram Generated"
              description="When a new diagram is created"
              checked={settings.notifications.diagramGenerated}
              onChange={() => toggleNotification('diagramGenerated')}
            />
            <SettingRow
              label="Requirement Extracted"
              description="When requirements are found in Slack"
              checked={settings.notifications.requirementExtracted}
              onChange={() => toggleNotification('requirementExtracted')}
            />
            <SettingRow
              label="Approval Needed"
              description="When items need your review"
              checked={settings.notifications.approvalNeeded}
              onChange={() => toggleNotification('approvalNeeded')}
            />
            <SettingRow
              label="Weekly Digest"
              description="Summary of weekly activity"
              checked={settings.notifications.weeklyDigest}
              onChange={() => toggleNotification('weeklyDigest')}
            />
          </div>
        </div>
      </div>

      <div className="mt-6 rounded-2xl border border-slate-200 bg-white p-6">
        <h2 className="font-semibold text-slate-900">Connected Integrations</h2>
        <p className="mb-4 text-sm text-slate-500">Manage your connected services</p>
        <div className="grid grid-cols-1 gap-4 sm:grid-cols-3">
          <IntegrationCard
            icon={ChatIcon}
            iconColorClass="bg-purple-50 text-purple-600"
            name="Slack"
            value={mostRecentProject?.integrations.slack}
            project={mostRecentProject}
          />
          <IntegrationCard
            icon={DocumentIcon}
            iconColorClass="bg-amber-50 text-amber-600"
            name="Asana"
            value={mostRecentProject?.integrations.asana}
            project={mostRecentProject}
          />
          <IntegrationCard
            icon={GitBranchIcon}
            iconColorClass="bg-slate-100 text-slate-600"
            name="GitHub"
            value={mostRecentProject?.integrations.github}
            project={mostRecentProject}
          />
        </div>
      </div>

      <div className="mt-6 grid grid-cols-1 gap-6 lg:grid-cols-2">
        <div className="rounded-2xl border border-slate-200 bg-white p-6">
          <div className="mb-4 flex items-center gap-2">
            <PaletteIcon className="h-5 w-5 text-slate-400" />
            <h2 className="font-semibold text-slate-900">Preferences</h2>
          </div>
          <div className="space-y-4">
            <div>
              <label className="mb-1.5 block text-sm font-semibold text-slate-900">Language</label>
              <select
                name="language"
                value={preferencesDraft.language}
                onChange={handlePreferenceChange}
                className={selectClass}
              >
                <option>English</option>
                <option>Arabic</option>
              </select>
            </div>
            <div>
              <label className="mb-1.5 block text-sm font-semibold text-slate-900">Theme</label>
              <select
                name="theme"
                value={preferencesDraft.theme}
                onChange={handlePreferenceChange}
                className={selectClass}
              >
                <option>Light</option>
                <option>Dark</option>
              </select>
            </div>
            <div>
              <label className="mb-1.5 block text-sm font-semibold text-slate-900">Date Format</label>
              <select
                name="dateFormat"
                value={preferencesDraft.dateFormat}
                onChange={handlePreferenceChange}
                className={selectClass}
              >
                <option>MM/DD/YYYY</option>
                <option>DD/MM/YYYY</option>
                <option>YYYY-MM-DD</option>
              </select>
            </div>
          </div>
          <button
            onClick={handleSavePreferences}
            className="mt-5 rounded-lg bg-teal-500 px-5 py-2.5 font-semibold text-white transition hover:bg-teal-400"
          >
            {justSaved ? 'Saved ✓' : 'Save Changes'}
          </button>
        </div>

        <div className="rounded-2xl border border-red-200 bg-white p-6">
          <h2 className="font-semibold text-red-600">Danger Zone</h2>
          <div className="mt-4 flex items-center justify-between gap-4">
            <div>
              <p className="font-medium text-slate-900">Delete All Data</p>
              <p className="text-sm text-slate-500">Permanently delete all project data</p>
            </div>
            <button
              onClick={handleDeleteAllData}
              className="flex shrink-0 items-center gap-2 rounded-lg bg-red-600 px-4 py-2.5 font-semibold text-white transition hover:bg-red-500"
            >
              <TrashIcon className="h-4 w-4" />
              Delete
            </button>
          </div>
        </div>
      </div>
    </div>
  )
}
